<a href="https://colab.research.google.com/github/bbini1109/python_workspace/blob/master/p200_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy
- NumPy는 Numerical Python의 줄임말로, 파이썬에서 산술 계산을 위한 가장 필수 패키지중 하나이다.
- 과학 계산을 위한 대부분의 패키지는 NumPy의 배열 객체를 데이터 교환을 위한 공통 언어처럼 사용한다.
- 효율적인 다차원 배열인 ndarray(n dimensional array)는 빠른 배열 계산과 유연한 브로드캐스팅 기능을 제공한다.
- 반복문을 작성할 필요 없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수이다.
- 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 적재된 파일을 다루는 도구이다.
- 선형대수, 난수 생성기등에 사용된다.
- C, C++, 포트란으로 작성한 코드를 연결할 수 있는 C API가 제공된다.

공식문서 https://numpy.org/doc/stable/  
numpy 100 문제 https://github.com/rougier/numpy-100


### 1.데이터 생성


In [ ]:
#!pip install numpy 
import numpy as np

In [ ]:
a = np.zeros(3) # 1차원 배열 -> 벡터

In [ ]:
a

array([0., 0., 0.])

In [ ]:
# 처음 객체들은 type(), dir()을 해본다.
print(type(a))
print(dir(a))

<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__r

In [ ]:
# 1차원 배열 = 벡터
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
print(type(a))
print(dir(a))
print(len(dir(a)))

<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__r

In [ ]:
# 2차원 배열 = 행렬
b = np.array([[1,2], [3,4]])
b

array([[1, 2],
       [3, 4]])

In [ ]:
# 3차원 배열 이상 = 텐서(tensor)
c = np.array([[[1,2], [3,4]],
              [[5,6], [7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
# 문자 데이터가 하나라도 있으면 전체가 문자로 바뀐다.
# numpy는 homogeneous 이다.
a = np.array([1,'2', 3])
print(a)
print(type(a))
print(type(a[0]))

['1' '2' '3']
<class 'numpy.ndarray'>
<class 'numpy.str_'>


In [ ]:
b = np.array(['a',1, True])
print(b)
print(type(b))
b

['a' '1' 'True']
<class 'numpy.ndarray'>


array(['a', '1', 'True'], dtype='<U21')

In [ ]:
c = np.array([1,True,2, False]) # 논리값은 숫자로 바뀜 True=1 False=0
print(c)
print(type(c))
c
print(type(c[0]))

[1 1 2 0]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


### np.zeros
- tuple로 인자를 넣으면 그대로 모양을 만든다.
-(2,3) : 2행 3열 행렬을 만든다.
- zeros는 기본값으로 0.으로 값을 모두 채운다.  
 a = np.zeros([2,3])  
 a = np.zeros((2,3))

In [ ]:
a = np.zeros([2,3])
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a = np.zeros([2,3,4]) #([갯수, 행, 열])
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### np.eye
- eye는 단위 행렬
- 숫자만 사용할 수 있다.

In [ ]:
# 인자값이 1개이면 행과 열이 같다.
# 3행 3열 행렬을 생성한다.
# 단위 행렬은 1과 0으로 채워진다.
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# eye는 행과 열의 크기를 지정할 수 있다.
# 3행 2열 행렬 생성
a = np.eye(3, 2)
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
# 크기(1)가 시작되는 위치를 지정할 수 있다.
# k는 열의 위치값을 정해준다.
# 이런게 있구나 정도만 알고 넘어가기
c = np.eye(3,4, k=1)
c

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### np.identity
- 수학에서 단위행렬은 영어로 identity matrix
- 크기 한개만 지정해서 생성할 수 있다.

In [ ]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# TypeError
# 인자 하나만 넣을 수 있..
a = np.identity(3,2) # 크기 한개만 지정해서 생성가능
a

TypeError: ignored

### np.full
- 지정한 크기의 배열을 생성하고 채울값을 지정한다.
- 2행 2열의 배열 생성 후 1로 채워준다.  
  np.full((2,2,)1)

In [ ]:
a = np.full((2,2),1)
a

array([[1, 1],
       [1, 1]])

In [ ]:
b = np.full(3,4)
b

array([4, 4, 4])

In [ ]:
c = np.full((2,2), [1,2]) # 채워지는 값을 배열로
c

array([[1, 2],
       [1, 2]])

In [ ]:
d = np.full((2,2), [[1,2],[3,4]])
d

array([[1, 2],
       [3, 4]])

### np.empty
- 배열을 생성하고 초기화를 지정하지 않는다.
- 메모리에 있는 겂이나 이전에 사용했던 값들로 채워진다.

In [ ]:
a = np.empty(3)
a

array([2.61364363e-316, 0.00000000e+000, 2.37151510e-322])

In [ ]:
k = np.zeros((2,3))
k

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# zeros해서 생성한 배열이 있으면 배열의 값을 0으로 채워준다.
b = np.empty((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
c = np.empty((2,5))
c

array([[2.55436129e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 4.49576298e+251],
       [9.95866276e-043, 1.74247934e-076, 7.17952962e-091,
        2.14463043e+184, 8.78739118e-153]])

### np.ones
- 배열의 모든 값을 1로 채운다.

In [ ]:
# 1행 3열의 배열 생성 후, 모든 값을 1로 채운다.
a = np.ones(3)
a

array([1., 1., 1.])

In [ ]:
# b= np.ones([2,3])
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

### _like
- _like가 붙으면 shape가 같게 만들어진다.
- 연산하기 위해서 shape를 맞춰야 하는 경우가 있다.

In [ ]:
a = np.array([[1,2,3,], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.shape

(2, 3)

In [ ]:
b = np.empty_like(a)
b

array([[52401936,        0,        0],
       [       0,        0,        0]])

In [ ]:
c = np.eye(2)
c

array([[1., 0.],
       [0., 1.]])

In [ ]:
c.shape

(2, 2)

In [ ]:
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
d.shape

(3, 3)

In [ ]:
# ValueError 서로 값이 맞지 않으면 발생함
c + d

ValueError: ignored

### linspace
- 동등한 간격으로 값을 생성한다.
- 0부터 49까지 50개가 생성된다면 세번째 num 인가 값이 생략되어 있으므로 start와 end 계산해서 default 50이 생성된다.
- linspace(start, end, num)
- linspace(0, 49) #num = 50

In [ ]:
a = np.linspace(0, 49)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [ ]:
b = np.linspace(0, 20)
b

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [ ]:
len(b)

50

In [ ]:
# 1부터 10까지 3개의 요소를 생성한다.
# 기본은 endpoint=True로 설정되어 있기 때문에 10이 포함된다.
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [ ]:
# 1부터 10미만 사이에서 3개의 요소를 생성한다.
# endpoint=False로 설정되어 있으므로 10이 포함이 안된다.
np.linspace(1, 10, 3, endpoint=False)

array([1., 4., 7.])

### logspace 
- linspace와 비슷하다.
- log scale을 사용하는 차이가 있다.
- 1 부터 50까지 사이의 10개의 요소를 생성한다.
- np.logspace(1,50,10)

In [ ]:
a = np.logspace(1, 50, 10)
a

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

### dtype
- numpy는 c언어를 기반으로 해서 만들었기 때문에 c의 데이터 타입을 차용할 수 있다.

In [ ]:
a = np.array([1,2,3,])
a

array([1, 2, 3])

In [ ]:
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


In [ ]:
b = np.array([1,2,3], dtype=np.int8)
b

array([1, 2, 3], dtype=int8)

In [ ]:
# np.int8은 -128 ~ 127 사이의 값을 지정할 수 있다.
c = np.array([-127, -128, 17, 2, 3, -127, -128, 127 ], dtype=np.int8) #numpy의 데이터타입 지정 방식
c

array([-127, -128,   17,    2,    3, -127, -128,  127], dtype=int8)

In [ ]:
# int는 python의 int를 사용한다.
d = np.array([127, 2, 3, -127, -128], dtype=int) #python의 데이터타입 지정 방식
d

array([ 127,    2,    3, -127, -128])

In [ ]:
type(d[0])

numpy.int64

### python 도움말

In [ ]:
?sum

In [ ]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



### numpy의 도움말

In [ ]:
np.lookfor('sum')

Search results for 'sum'
------------------------
numpy.sum
    Sum of array elements over a given axis.
numpy.cumsum
    Return the cumulative sum of the elements along a given axis.
numpy.einsum
    einsum(subscripts, *operands, out=None, dtype=None, order='K',
numpy.nansum
    Return the sum of array elements over a given axis treating Not a
numpy.nancumsum
    Return the cumulative sum of array elements over a given axis treating Not a
numpy.einsum_path
    Evaluates the lowest cost contraction order for an einsum expression by
numpy.trace
    Return the sum along diagonals of the array.
numpy.ma.sum
    Return the sum of the array elements over the given axis.
numpy.Bytes0.sum
    Scalar method identical to the corresponding array attribute.
numpy.polyadd
    Find the sum of two polynomials.
numpy.ma.cumsum
    Return the cumulative sum of the array elements over the given axis.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.Bytes0.cumsum
    Scal

In [ ]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.shape

(2, 3)

In [ ]:
# 몇 차원 배열인지 알려줌
# shape로도 알 수 있다.
a.ndim

2

In [ ]:
# 데이터 타입을 알려준다.
a.dtype

dtype('int64')

In [ ]:
# 요소 전체의 개수를 알려준다.
# shape로도 알 수 있다.
a.size

6

In [ ]:
# 각 요소당 차지하는 byte수를 알려준다.
a.itemsize

8

### numpy와 python의 속도 차이(이런게 있구나 정도만 알기)

In [ ]:
#range와 같은 역할
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# numpy를 이용한 계산
%time np.sum(np.arange(1000000000))


CPU times: user 1.95 s, sys: 1.89 s, total: 3.84 s
Wall time: 4.34 s


499999999500000000

In [ ]:
# python을 이용한 계산
%time sum(range(1000000000))

CPU times: user 20.3 s, sys: 0 ns, total: 20.3 s
Wall time: 20.8 s


499999999500000000

같은 np.sum()을 사용하더라도 값을 생성하는 방법에 따라 속도가 달라진다.

In [ ]:
# %time np.sum(range(1000000000)) # 오래 걸린다.

NameError: ignored

### copy
※ 대입문 6가지  
 a = 1  
 a = b = 1  
 a, b = 1, 2  
 a, * b = 1,2, 3  
 a += 1  
 global, nonlocal


### python copy

In [ ]:
a = [1,2,3] #sequence 데이터, mutable, heterogeneous(다른 타입의 데이터 저장 가능)

In [ ]:
b = a

In [ ]:
b

[1, 2, 3]

In [ ]:
a is b # 메모리 주소 비교

True

In [ ]:
# a와 b가 메모리 주소를 공유
# b값을 변경하면 a도 같이 변경이 된다.
b[0] = 7

In [ ]:
b

[7, 2, 3]

In [ ]:
a

[7, 2, 3]

list copy()

In [ ]:
a = [1,2,3 ]

In [ ]:
# copy()는 똑같은 값만 가지고 메모리는 공유하지 않는다.
b = a.copy()

In [ ]:
a is b # 메모리 주소

False

In [ ]:
id(a)

140231022441472

In [ ]:
id(b)

140231022435920

In [ ]:
b[0] = 8

In [ ]:
b

[8]

In [ ]:
a

[1, 2, 3]

In [ ]:
print(a is b)
print(a == b)

False
False


list가 2차원 일 때  

In [ ]:
a = [[1,2,3]]

In [ ]:
type(a)

list

In [ ]:
# shallow copy 얇은 카피
b = a.copy()

In [ ]:
print(a is b)
print(a == b)

False
True


In [ ]:
print(a[0] is b[0]) # 주소가 복사되어서 같게 나옴
print(a[0] == b[0])

True
True


list deepcopy()

In [ ]:
import copy

In [ ]:
a = [[1,2,3]]
b = copy.deepcopy(a)

In [ ]:
print(a)
print(b)

[[1, 2, 3]]
[[1, 2, 3]]


In [ ]:
print(a is b)
print(a == b)
print(a[0] is b[0]) # deep copy가 됨
print(a[0] == b[0])

False
True
False
True


[:]는 전체라는 뜻이다.  
슬라이싱 방식으로 1차 리스트 일 때는 재할당 하면 deepcopy가 된다.  
슬라이싱 2차 리스트 이상인 경우 shallow copy가 발생한다.

In [ ]:
# 1차원
a = [1,2,3]
b = a[:]
print(a is b) # 1차원 deepcopy
print(a == b)
b[0] = 7
print(a is b) 
print(a == b) # 1차원 deepcopy

False
True
False
False


In [ ]:
a = [[1,2,3]]
# 슬라이싱 2차 이상인 경우 shallow copy가 된다.
b = a[:]
print(a is b)
print(a == b)
b[0][0] = 7
print(a is b) 
print(a == b) # shallow copy가 발생해서 a값도 바뀌어버린다.

False
True
False
True


※python의 copy는 기본적으로 2차원 부터 shallow copy를 한다.

### numpy의 copy

In [ ]:
import numpy as np
a = b = np.array([1,2,3])

In [ ]:
print(a is b)
print(a == b)

True
[ True  True  True]


array는 sequence타입으로 인덱싱과 슬라이싱이 가능하다.

In [ ]:
# indexing
a[0] #array는 인덱스 통해서 접근 가능

1

In [ ]:
# slicig
a[:]

array([1, 2, 3])

In [ ]:
# array는 mutable이다.
# 예외가 몇가지 있지만 mutable에 가깝다.
a[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


array는 homogeneous, sequence, mutable 이다.

array deepcopy

In [ ]:
a = np.array([1,2,3])
# numpy는 기본적으로 deepcopy이다.
b = a.copy()

In [ ]:
print(a is b)

False


### as 계열
다른 데이터 타입을 가져와서 바꿔서 사용할 때는 as라는 이름이 보통 붙는다.

In [ ]:
# python의 list 데이터 타입을 int ndarray로 변환
a = [1,2,3] # python의 list
print(type(a))
print(type(a[0]))

b = np.array(a) # numpy의 array로 변환
print(type(b))
print(type(b[0]))

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [ ]:
# python의 list 데이터 타입을 int ndarray로 변환 (asarray())
a = [1,2,3] # python의 list
print(type(a))
print(type(a[0]))

b = np.asarray(a) # numpy의 array로 변환
print(type(b))
print(type(b[0]))

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [ ]:
# python의 list 데이터 타입을 int ndarray로 변환 (asfarray())
a = [1,2,3] # python의 list
print(type(a))
print(type(a[0]))

b = np.asfarray(a) # numpy의 array로 변환 *float 실수 a가 정수이기 때문에 asfarray
print(type(b))
print(type(b[0]))

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [ ]:
# python의 list 데이터 타입을 int ndarray로 변환 (asfarray())
a = [1., 2., 3.] # python의 list
print(type(a))
print(type(a[0]))

b = np.asarray(a) # numpy의 array로 변환 *a가 실수이면 f 안넣어도 실수로 가져온다.
print(type(b))
print(type(b[0]))

<class 'list'>
<class 'float'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>


### 배열의 값 가져오기

####(1) comma로 값 가져오기  

In [ ]:
a = [[1,2,3], [4,5,6]] # python
b = np.array([[1,2,3], [4,5,6]]) # array

In [ ]:
a[0]

[1, 2, 3]

In [ ]:
a[0,1]

TypeError: ignored

In [ ]:
a[0][1]

2

In [ ]:
# 0 행에서 부터 1 미만
a[slice(0,1)] 

[[1, 2, 3]]

In [ ]:
# numpy
b[[0]]

array([[1, 2, 3]])

In [ ]:
b[0,1] # python은 각각 써줘야 한다. -> a[0][1]

2

#### (2) boolean indexing

In [ ]:
a = [[1,2,3,4]] # python list

In [ ]:
# TypeError
a>3

TypeError: ignored

In [ ]:
b = np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [ ]:
b>3

array([False, False, False,  True])

array를 scalar와 연산하면 elementwise로 계산한다.  
(elementwise : 원소별로 각각 계산이 된다.)

In [ ]:
b[b>3] # True인 값만 가져온다.

array([4])

numpy에서 boolean indexing 조건
- array만 가능하다.  
- numpyTrue, False로만 가능하다.
- shape이 맞아야한다.(개수가 맞을 때만 사용할 수 있다.)

####(3) fancy indexing

In [ ]:
b = np.arange(100).reshape([20,5]) # reshape(행, 열) 배열의 구조 변경
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [ ]:
b[:] # 전체를 가져온다. b[:,:]와 같다.
print(b[1])
print(b[1,2])
print(b[1:3])
print(b[1:3, 2:4])

# fancy indexing : 띄엄 띄엄 가져오고 싶은 것을 가져올 때
print(b[[1,3,5]]) # 1,3,5 행을 가져옴

print(b[[1,3,5],[0,2,4]])
print(b[:,[0,2,4]])

[5 6 7 8 9]
7
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 7  8]
 [12 13]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]]
[ 5 17 29]
[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]
 [25 27 29]
 [30 32 34]
 [35 37 39]
 [40 42 44]
 [45 47 49]
 [50 52 54]
 [55 57 59]
 [60 62 64]
 [65 67 69]
 [70 72 74]
 [75 77 79]
 [80 82 84]
 [85 87 89]
 [90 92 94]
 [95 97 99]]


In [ ]:
# fancy indexing은 인덱싱 기법만 사용할 수 있다.
# ':' (콜론)은 슬라이싱 기법이므로 지원하지 않는다.
b[[2:5]]

SyntaxError: ignored

fancy indexing을 할 때에는 인덱스 개수가 같게 지정되어야 한다.

In [ ]:
# 정상처리
b[[1,3,4],[0,2,1]]

array([ 5, 17, 21])

In [ ]:
# shape가 맞지 않으면 비정상 처리 IndexError
b[[1,3,5],[0,2]]

IndexError: ignored

### 3차원 이상에서 차원 구분

In [ ]:
b = np.arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
b[0] # 0번째 깊이

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[1] # 1번째 깊이

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
b[0,1] #0번째 깊이에서 1번째 행에 있는것을 가져와라

array([4, 5, 6, 7])

In [ ]:
b[0,1,3]

7

### fancy indexing과 indexing의 차이
- indexing은 원래 차원에서 하나 감소해서 가져오고 fancy indexing은 원래 차원 그대로 가져온다.

In [ ]:
b[0] # indexing 차원이 하나 감소해서 가져온다. (3차원 -> 2차원으로 가져옴)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[[0]] # fancy indexing 원래 3차원 그대로 가져온다.

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
#b[0]       #2차원
#b[0,:,:]   #2차원
b[[0],:,:]  #3차원

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

## Ellipsis

In [ ]:
b[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
type(...)

ellipsis

In [ ]:
b[0] # 생략기법(인덱싱 기법)
b[0,:,:] # 슬라이싱 기법
b[0,...] # Ellipsis 기법

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
# 숫자 1,5,9만 가져오기
b[0,:,1]

array([1, 5, 9])

In [ ]:
# 숫자 1,5,9,3,7,11 가져오기
b[0,:,[1,3]]

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [ ]:
# 숫자 4,5,6,7,16,17,18,19
b[:,1,:]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [ ]:
b[:, 1:2, :] # 3차원 그대로 가져온다.

array([[[ 4,  5,  6,  7]],

       [[16, 17, 18, 19]]])

In [ ]:
# 숫자 3,7,11,15,19,23 가져오기
b[:,:,3]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [ ]:
b[:,:,[3]] #3차원 그대로 가져온다.

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

### 줄임표현(...)
출력해야할 데이터 수가 엄청 클 때 보이는 ...은 Ellipssis와 다르다.

In [ ]:
# out에 나오는 ... 은 단순히 줄임표현이다.
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [ ]:
np.set_printoptions(edgeitems=6) # 양쪽에 표시할 숫자만큼 넣어주면 된다.
np.arange(100000)

array([    0,     1,     2,     3,     4,     5, ..., 99994, 99995, 99996,
       99997, 99998, 99999])

### 연산
numpy 연산의 기본은 두 개의 shape가 같아야 한다.

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.shape

(3, 4)

In [ ]:
b = np.arange(1,13).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b.shape

(3, 4)

numpy는 elementwise로 vectorize 연산을 한다.  
vectorize는 데이터의 연산을 일괄적으로 처리하는 기능이다.

In [ ]:
# 같은 위치의 요소끼리 더해 준다.(elementwise)   *list에서는 elementwise로 처리 안되고 연결로 처리된다.
# 각각 자리에 맞는 데이터들 끼리 연산이 되어 출력된다.
a+b

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [ ]:
# python list
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

numpy는 python함수도 vectorize 시키는 기능을 지원한다.

In [ ]:
@np.vectorize
def plus(a,b):
  return a+b

plus([1,2,3], [4,5,6])

array([5, 7, 9])

In [ ]:
a * b

array([[  0,   2,   6,  12],
       [ 20,  30,  42,  56],
       [ 72,  90, 110, 132]])

In [ ]:
#list에서는 안된다.
[1,2,3] * [4,5,6]

TypeError: ignored

행X열

In [ ]:
c = np.matrix([[1,2],[3,4]])
c

matrix([[1, 2],
        [3, 4]])

In [ ]:
type(c)

numpy.matrix

In [ ]:
c * c

matrix([[ 7, 10],
        [15, 22]])

In [1]:
import numpy as np

In [ ]:
#matrix * matrix = 행렬곱
# 1*1 + 2*3  1*2 + 2*4
# 3*1 + 4*3  3*2 + 4*4
c * c

matrix([[ 7, 10],
        [15, 22]])

In [ ]:
a = np.arange(1, 13).reshape(3,4)
print(a)
print(a.shape)


In [ ]:
b = np.arange(1,13).reshape(3,4)
print(b)
print(b.shape)

ndarray에서 행렬곱 연산자 @ 이다.  
python 재단에서 numpy를 위해 만들어준 연산자이다.

In [ ]:
a @ b

행렬곱을 하기 위해서는 shape가 맞아야한다.  
T는 transpose(전치)의 약자이다.

In [ ]:
b.T
b

In [ ]:
print(a.shape, b.shape)

In [ ]:
a @ b

함수방법으로 np.dot( )을 사용할 수 있다.

In [2]:
np.dot(a, a.T) #ndarray

NameError: ignored

In [ ]:
b = np.matrix(b) #matrix
type(b)

In [ ]:
np.dot(b, b.T)

In [ ]:
a.dot(a.T) #메소드 방식에서는 앞에 반드시 객체가 와야 한다. -> a.dot에서 'a'

### broadcasting
python은 배열과 숫자간에 연산을 할 수 있다.

In [4]:
[1,2,3] + 1 #python에서는 리스트와 숫자 연산 불가능

TypeError: ignored

In [5]:
a = np.array([1,2,3]) # 배열
a + 1 # 내부적으로 연산 가능(broadcasting)

array([2, 3, 4])

broadcasting이란 모양(shape)가 안 맞는데, 특정한 조건에 맞으면 모양을 같게 만들어 연산하는 기능이다.  
위 연산에서 1을 a에 같은 모양으로 만들어준다.

**shape 모양이 배차이가 나야만 broadcasting이 발생한다.***

reshape(2,3)  
array([3,4])

In [9]:
b = np.arange(6).reshape(2,3)
b # 2행 3열

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
c = np.array([3,4])
c # 1행 2열

array([3, 4])

### axis
axis는 다차원 배열을 연산 할 때 기준이 되는 축이다.

In [13]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
np.sum(a)

66

In [16]:
np.sum(a, axis=0) # a는 2차원 배열, 2차원 배열에서 0은 행이 기준 -> 행을 기준으로 누적(행마다) 위에서 아래로 0+4+8, 1+5+9, 2+6+10, 3+7+11

array([12, 15, 18, 21])

In [20]:
np.sum(a, axis=1) # a배열은 2차원이므로 axis = 1은 열을 기준으로 누적(열마다) 오른쪽에서 왼쪽으로

array([ 6, 22, 38])

3차원 이상에서 축기준 계산

In [22]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [24]:
np.sum(a,axis=0) # 3차원 배열에서 axis = 0 이면, 1대1 매칭으로 누적, 공간기준(공간마다)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [26]:
np.sum(a, axis=1) # 행기준(행마다)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [27]:
np.sum(a, axis=2) # 열기준(열마다)

array([[ 6, 22, 38],
       [54, 70, 86]])

### array 모양 바꾸기  

#### (1) reshape
reshape는 차원을 바꿔주는 기능을 한다.

In [29]:
a = np.arange(24)
b = a.reshape(3,8)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [30]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [32]:
a.reshape(2,3,5)

ValueError: ignored

In [35]:
# 음수를 쓰면, 알아서 shape을 맞춘다.
a.reshape(2, 3, -1) # '-'값을 주면 알아서 모양을 만들어준다.

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
a.reshape(2, 3, -100) # 음수값은 어떤 값을 줘도 상관없다.(숫자 크기에 상관없음)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [38]:
# 고정된 값을 줄 때 배열의 크기를 고려해서 준다.
a.reshape(3, 5, -1) # 고정값을 잘 맞춰줘야한다. 음수값은 한개만 사용해야 하고, 위치는 상관없다.

ValueError: ignored

In [40]:
 # 음수값은 한개만 사용해야 한다.
 # 음수는 다른 차원들이 정해준 상황에서 남은 하나의 차원만 알아서맞춰준다.
a.reshape(3, -1, -1)

ValueError: ignored

In [42]:
# 음수값이 1개이면 위치는 어디에 오든 상관없다.
a.reshape(3, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [44]:
a.reshape(-1, 4, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

####(2) reshape로 차원 늘리기

In [46]:
# 1차원 -> 2차원
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [47]:
# 1차원 -> 3차원
a = np.arange(6).reshape(1,3,2)
a

array([[[0, 1],
        [2, 3],
        [4, 5]]])

### resize

In [51]:
# size는 원소의 개수를 알려준다.
a = np.arange(24)
print(a.size)
print(len(a))

24
24


In [53]:
# mutable이다. return이 없고 자기 자신을 바꾼다. -> reshape와 차이점 1
# 원래의 원소 개수와 변경하는 원소 개수가 안맞아도 된다.(0으로 채워준다.) -> reshape와 차이점 2
b = np.arange(24)
b.resize((2,3,8))
b

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]],

       [[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0]]])

### array 쪼개기

split

In [67]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [68]:
# indices_or_sections
a = np.split(a, 3, axis=0)
print(a)
print(type(a))
print(a[0], type(a[0]))

[array([0, 1, 2, 3, 4, 5, 6, 7]), array([ 8,  9, 10, 11, 12, 13, 14, 15]), array([16, 17, 18, 19, 20, 21, 22, 23])]
<class 'list'>
[0 1 2 3 4 5 6 7] <class 'numpy.ndarray'>


hsplit & vsplit

split은 axis 파라미터가 있다. default:axis=0

In [72]:
a = np.arange(24)
b = a.reshape(4, 6)
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [74]:
np.split(b, 2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [76]:
np.split(b, 2, axis=0) # 2차원으로 쪼개짐

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [78]:
np.hsplit(a, 2) # 수평, 1차원으로 쪼개짐

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

In [79]:
np.split(b, 2, axis=1)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [81]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [82]:
np.hsplit(b,2)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

indices_or_sections
- split 시리즈 함수들의 두번째 파라미터 이름이 indices_or_sections이다.
- 숫자를 묶어서 넣으면 구간으로 쪼개진다.

In [84]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [86]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [87]:
# section
# 처음부터 ~ 2미만 : [0,1]
# 2부터 ~ 3미만 : [2]
# 3부터 ~ 끝까지 : [3,4,5,...23]
np.hsplit(a, (2,3)) # 앞에는 2 미만까지 ->[0,1]/2에서 3미만까지 ->[2]/ 나머지 ->[나머지숫자들]


[array([0, 1]),
 array([2]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20, 21, 22, 23])]

### array 합치기

In [90]:
a = np.arange(24)
x, y, z = np.split(a, 3)

a = np.arange(25)  
x, y, z = np.split(a, 3)

-> 이런경우 모양이 안맞아서 오류난다. 25가 3으로 나눠떨어지지 않기 때문에.  
-> 배열은 모양 맞추는것이 중요

In [91]:
print(x)
print(y)
print(z)

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]
[16 17 18 19 20 21 22 23]


hstack & vstack

In [93]:
np.hstack((x,y))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [95]:
np.vstack((x,y)) # 열단위로 합쳐짐

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

dstack
- dstack은 합쳐서 3차원으로 만들어준다.
- 합칠 array들이 1차원,2차원일 경우는 차원을 늘린 후 합친다.
- 합쳐지는 차원은 axis=2이다.

In [97]:
# 1차원
print(x)
print(y)

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]


In [100]:
# 3차원
c = np.dstack((x,y))
c


array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11],
        [ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])

In [101]:
c.shape

(1, 8, 2)

In [102]:
x = x.reshape(2,4)
y = y.reshape(2,4)

In [104]:
print(x)
print(y)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [107]:
c = np.dstack((x,y))
c

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11]],

       [[ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])

In [108]:
c.shape

(2, 4, 2)

### concatenate
concatenate은 axis 방향에 그대로 합쳐준다.  
※ stack은 axis 방향에 새로운 차원을 만들어 합쳐준다.

In [109]:
a = np.arange(12).reshape(3,4)
x, y = np.split(a, 2, axis=1)

In [111]:
print(x)
print(y)

[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [113]:
# 원래 shape 크기 그대로 유지를 한다.
np.concatenate((x,y)) # axis = 0

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [ 2,  3],
       [ 6,  7],
       [10, 11]])

In [115]:
# shape 크기를 1개 증가해서 합친다. -> 차원이 +1 됨
np.stack((x,y)) # axis = 0

array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]])

기억해야 할 것 두가지  
- mutable이 되는지  
- 차수가 어떻게 변하는지

#### 차원 확장

reshape

In [116]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

stack  
나누기

In [120]:
# 3차원으로 확장
# tuple에 원소가 1개 있으면 차원만 확장 시켜준다.
np.stack((a,)) # tuple로 넣어주면 1차원 늘어남

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

newaxis
- 인덱싱 할 때 np.newaxis를 쓰면 차원을 늘릴 수 있다.

In [121]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [123]:
a.shape

(3, 4)

In [125]:
a[0] # 인덱싱

array([0, 1, 2, 3])

In [127]:
# 2차원 -> 3차원
a[np.newaxis]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

슬라이싱을 할 때, np.newaxis를 쓰면 차원을 늘릴 수 있다.

In [130]:
a[:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [132]:
# 2차원 -> 3차원
# (1,3,4) (공간, 행, 열)
a[np.newaxis,:]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [134]:
# 행의 값이 늘어남
# (3,1,4)
a[:,np.newaxis]

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [135]:
a[:,np.newaxis].shape

(3, 1, 4)

In [137]:
# 열단위로 하나하나 생성됨. 각 행에 열 하나
# (3,4,1)
a[:,:,np.newaxis]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

In [139]:
a[:,:,np.newaxis].shape

(3, 4, 1)

In [140]:
# np.newaxis 자리에 None을 써도 되냐
np.newaxis is None 

True

np.newaxis 대신에 None을 써도 된다.  
None은 직관적이지 않고 헷갈려서 np.newaxis를 만들었다.  
numpy를 만들 때 python의 모든 연산자를 다 사용해서 남은 연산자가 없었다.  
그래서 None을 이용했다.

In [144]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

expand_dims

In [148]:
# 1공간 3행 4열
# a[np.newaxis:,:]와 같다.
np.expand_dims(a, 0)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [150]:
# 3공간 1행 4열
np.expand_dims(a, 1) #a[:,np.newaxis,:]와 같다.

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [152]:
# 3공간 4행 1열
np.expand_dims(a, 2) # a[:,:,np.newaxis]와 같다.

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

### array 한줄로 펴기

flatten

In [154]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [156]:
# flatten( )은 결과를 return하고 메모리의 값은 변경되지 않는다.
b = a.flatten()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [159]:
# flatten 후에도 원래 값은 그대로 가져온다.
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [158]:
# flatten 후에도 원래 값은 그대로 가져온다.
a[2]

array([ 8,  9, 10, 11])

swapaxes

In [163]:
a = np.array([[1],[2]]) # 2차원 2행 1열의 배열 생성
a

array([[1],
       [2]])

In [164]:
a.shape

(2, 1)

In [166]:
# a의 0번 차원과 1번 차원을 서로 바꾼다.
b = np.swapaxes(a, 1, 0) # 2차원 1행 2열의 배열 생성
b

array([[1, 2]])

In [167]:
a.T

array([[1, 2]])